DROP TABLE IF EXISTS sensor_data;

CREATE TABLE sensor_data (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  temperature INTEGER NOT NULL,
  humidity INTEGER NOT NULL
);